/* policy.h.  Generated by configure.  */
/* policy.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define if you have <sys/wait.h> that is POSIX.1 compatible.  */
#define HAVE_SYS_WAIT_H 1

/* Define if utime(file, NULL) sets file's timestamp to the present.  */
#define HAVE_UTIME_NULL 1

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef pid_t */

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if your <sys/time.h> declares struct tm.  */
/* #undef TM_IN_SYS_TIME */

/* Define if you have the mktime function.  */
#define HAVE_MKTIME 1

/* Define if you have the select function.  */
#define HAVE_SELECT 1

/* Define if you have the socket function.  */
#define HAVE_SOCKET 1

/* Define if you have the stime function.  */
#define HAVE_STIME 1

/* Define if you have the strdup function.  */
#define HAVE_STRDUP 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define if you have the strftime function.  */
#define HAVE_STRFTIME 1

/* Define if you have the strstr function.  */
#define HAVE_STRSTR 1

/* Define if you have the strtod function.  */
#define HAVE_STRTOD 1

/* Define if you have the strtol function.  */
#define HAVE_STRTOL 1

/* Define if you have the <fcntl.h> header file.  */
#define HAVE_FCNTL_H 1

/* Define if you have the <limits.h> header file.  */
#define HAVE_LIMITS_H 1

/* Define if you have the <sys/ioctl.h> header file.  */
#define HAVE_SYS_IOCTL_H 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <syslog.h> header file.  */
#define HAVE_SYSLOG_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the dbm library (-ldbm).  */
/* #undef HAVE_LIBDBM */

/* Define if you have the gdbm library (-lgdbm).  */
/* #undef HAVE_LIBGDBM */

/* Define if you have the db library (-ldb).  */
/* #undef HAVE_LIBDB */

/* Define if you have Swiss charge info */
/* #undef ISDN_CH */

/* Define if you have Austrian charge info */
/* #undef ISDN_AT */

/* Define if you have Netherlands charge info */
/* #undef ISDN_NL */

/* Define the config directory */
/* #undef I4LCONFDIR */

/* Define the old config directory */
#define OLDCONFDIR "/etc/isdnlog"

/* Define the name of the old config file */
#define OLDCONFFILE "isdnlog.conf"

/* Define the data directory */
#define DATADIR "/usr/lib/isdn"

/* Define if libarea should be used */
#define LIBAREA 1

/* Define if postgres should be used */
/* #undef POSTGRES */

/* Define if mysql should be used */
/* #undef MYSQLDB */

/* Define if server port */
#define SERV_PORT 20011

/* File for permission configuration */
#define USERFILE "isdnlog.users"

/* Logfile */
#define LOGFILE "/var/log/isdn.log"

/* Charge file */
#define CHARGEFILE "charge.dat"

/* Command for reloading */
#define RELOADCMD "reload"

/* Command for stopping */
#define STOPCMD "stop"

/* Command for rebooting */
#define REBOOTCMD "/sbin/reboot"

/* Use CDB instead of g?dbm? */
/* rename tools/cdb/i4l_cdb.c, if you want to use gdbm */
#define USE_CDB 1
