TOPDIR := ../..

SUBDIRS = basic digest

O_TARGET = auth.o
SOURCES = auth.c
LIBS = basic/libbasic.o digest/libdigest.o

#**********************
#bin_PROG = prog
#prog_SOURCE = prog.c xxx.c yyy.c
#prog_LIB = prog.o xxx.a yyy.a
#**********************


#**********************
#test_PROG = mytest
#mytestg_SOURCE = prog.c xxx.c yyy.c
#mytest_LIB = prog.o xxx.a yyy.a
#**********************



CFLAGS =
DEFS   = 
INCLUDE = 

LDFLAGS =
LDLIBS  = 

include $(TOPDIR)/rules.mk
