.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.\" Copyright (C) 1996 Erick Branderhorst <branderh@debian.org>
.\"
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2, or (at your option) any later
.\" version.
.\" 
.\" This is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\" A copy of the GNU General Public License is available as
.\" `/usr/share/common-licenses/GPL' in the Debian GNU/Linux distribution
.\" or on the World Wide Web at `http://www.gnu.org/copyleft/gpl.html'.
.\" You can also obtain it by writing to the Free Software Foundation,
.\" Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
.\"
.\" This manpage is created thanks to:
.\" Kai Henningsen <kai@khms.westfalen.de>,
.\" Ian Jackson <iwj10@cus.cam.ac.uk>,
.\" David H. Silber <dhs@firefly.com> &
.\" Carl Streeter <streeter@cae.wisc.edu>.
.\"
.TH IPROUTE 8 "June 1999" "Debian Project" "Debian Linux"
.SH NAME
ip, rtmon, rtacct, routef, routel \- No manpage available.
.SH DESCRIPTION
This program does not have a useful manpage.
When a manpage becomes available it will be included.
If you are a competent and accurate writer and are willing to spend
the time reading the source code and writing good manpages please
write a better man page than this one. Please 
.B contact 
the 
.B package maintainer 
in order to avoid several people working on the same manpage.

You can start reading the very good documents
available in the /usr/share/doc/iproute/ directory, in
.B .ps, .dvi
and
.B .tex
formats.

In particular, you can find the
.B IP command reference manual
in the
.B /usr/share/doc/iproute/ip-cref.*
files.

To read
.B ip-cref.dvi
run
.B xdvi ip-cref.ps
and to read
.B ip-cref.ps
run
.B gv ip-cref.ps.
.SH SEE ALSO
.BR dvips (1),
.BR gv (1x),
.BR latex (1),
.BR undocumented (7).
.SH AUTHOR
This manpage has been written by Roberto Lumbreras <rover@debian.org>,
using the
.BR undocumented (7)
manpage, written by Erick Branderhorst <branderh@debian.org>.
.SH THANKS
Kai Henningsen,
Ian Jackson,
David H. Silber,
Carl Streeter.

