.\" $Id: efthosts.5,v 1.2 1999/07/01 18:00:26 he Exp $
.\" SCCSID: @(#)$Original-Id: ftphosts.5,v 1.2 1997/01/10 06:27:02 sob Exp $
.\" based on ftphosts.5 1.2 1/26/93
.\" 
.TH efthosts 5 
.SH Name
efthosts \- eftd individual user host access file
.SH Description
The efthosts file is used to allow or deny access to certain
accounts from various hosts.
.SH Access Capabilities
.TP 0.5i
.B allow <username> <addrglob> [<addrglob> ...]
Only allow host(s) matching <addrglob> to log in as <username>.
.TP 0.5i
.B deny <username> <addrglob> [<addrglob> ...]
Always deny host(s) matching <addrglob> to log in as <username>.
.SH Files
/etc/isdn/efthosts
.SH See Also
.BR eftd(8) ,
.BR eftaccess(5) ,
.BR eft_wuauth(5)
