TOPDIR := ../..

SUBDIRS = methods soap xmltool

O_TARGET = handler.o

SOURCES = handler.c cpe_task_list.c cpe_req_list.c

LIBS = methods/libmethods.o soap/libsoap.o xmltool/libxmltool.o

#**********************
#bin_PROG = prog
#prog_SOURCE = prog.c xxx.c yyy.c
#prog_LIB = prog.o xxx.a yyy.a
#**********************
bin_PROG =

#**********************
#test_PROG = mytest
#mytestg_SOURCE = prog.c xxx.c yyy.c
#mytest_LIB = prog.o xxx.a yyy.a
#**********************
test_PROG = 

CFLAGS =
DEFS   = 
INCLUDE = 

LDFLAGS =
LDLIBS  = 

include $(TOPDIR)/rules.mk
