TOPDIR := ../../..

SUBDIRS =

O_TARGET = methods.o

SOURCES = inform.c param_attri.c object.c set_param_val.c get_param_val.c transfercomplete.c soap_fault.c download.c upload.c reboot.c get_param_name.c getrpcmeth.c

#**********************
#bin_PROG = prog
#prog_SOURCE = prog.c xxx.c yyy.c
#prog_LIB = prog.o xxx.a yyy.a
#**********************
bin_PROG =

#**********************
#test_PROG = mytest
#mytestg_SOURCE = prog.c xxx.c yyy.c
#mytest_LIB = prog.o xxx.a yyy.a
#**********************
test_PROG = 

CFLAGS =
DEFS   = 
INCLUDE = 

LDFLAGS =
LDLIBS  = 

include $(TOPDIR)/rules.mk
