/* 
 * Copyright (C) 2000-2001 Computer & Communications Research Laboratories,
 *			   Industrial Technology Research Institute
 */
/*
 * sip_cm.h
 *
 * $Id: sip_cm.h,v 1.38 2006/11/02 06:33:13 tyhuang Exp $
 */

#ifndef SIP_CM_H
#define SIP_CM_H

#ifdef  __cplusplus
extern "C" {
#endif

#include <common/cm_def.h>

#define SIP_TCP_DEFAULT_PORT		5060
#define SIP_FILENAME_MAX_LENGTH		32	
#define SIP_DOMAINNAME_MAX_LENGTH	32
#define SIP_MAX_VERSION_LENGTH		10
#define SIP_MAX_STATUS_CODE_LENGTH	256
#define SIP_MAX_REASON_LENGTH		128
#define SIP_MAX_REQUEST_URI_LENGTH	256
#define SIP_MAX_CONTENTLENGTH		15361
#define SIP_MAX_HDRLENGTH			1024
#define SIP_MAX_TIMER_COUNT			4096

#define	SIP_SOCKET_TIMEOUT		-2


typedef enum {
	SIP_OK				= RC_BASE_SIP,
	SIP_PASER_ERROR			= RC_BASE_SIP+100,
	SIP_GENERAL_ERROR,
	SIP_RFC822PARSE_ERROR,
	SIP_REQUESTLINE_ERROR,
	SIP_REQUESTURL_NULL,
	SIP_METHORD_NOT_SUPPORTED,
	SIP_VERSION_ERROR,
	SIP_ACCEPT_ERROR		= RC_BASE_SIP+200,
	SIP_ACCEPTENCODING_ERROR,
	SIP_ACCEPTLANGUAGE_ERROR,
	SIP_ALERTINFO_ERROR, /* add by tyhuang */ 
	SIP_ALLOW_ERROR,
	SIP_ALLOWEVENTS_ERROR,
	SIP_AUTHENTICATIONINFO_ERROR,
	SIP_AUTHORIZATION_ERROR,
	SIP_CALLID_ERROR,
	SIP_CALLINFO_ERROR, /* add by tyhuang */ 
	SIP_CLASS_ERROR,  /* add by tyhuang */ 
	SIP_CONTACT_ERROR,
	SIP_CONTENTDISPOSITION_ERROR,
	SIP_CONTENTENCODING_ERROR,
	SIP_CONTENTLANGUAGE_ERROR,
	SIP_CONTENTLENGTH_ERROR,
	SIP_CONTENTTYPE_ERROR,
	SIP_CSEQ_ERROR,
	SIP_DATE_ERROR,
	SIP_ENCRYPTION_ERROR,
	SIP_ERRORINFO_ERROR, /* add by tyhuang*/
	SIP_EXPIRES_ERROR,
	SIP_FROM_ERROR,
	SIP_HIDE_ERROR,
	SIP_INREPLYTO_ERROR,	/*add by tyhuang*/
	SIP_MAXFORWARD_ERROR,
	SIP_MIMEVERSION_ERROR, /* add by tyhuang*/
	SIP_MINEXPIRES_ERROR,  /* add by tyhuang*/
	SIP_MINSE_ERROR,	/* add by tyhuang 2004/4/19 */
	SIP_ORGANIZATION_ERROR,
	SIP_PASSERTEDIDENTITY_ERROR,
	SIP_PPREFERREDIDENTITY_ERROR,
	SIP_PRIORITY_ERROR,
	SIP_PRIVACY_ERROR,
	SIP_PROXYAUTHENTICATE_ERROR,
	SIP_PROXYAUTHORIZATION_ERROR,
	SIP_PROXYREQUIRE_ERROR,
	SIP_RACK_ERROR,
	SIP_RECORDROUTE_ERROR,
	SIP_REPLYTO_ERROR,
	SIP_REQUIRE_ERROR,
	SIP_RESPONSEKEY_ERROR,
	SIP_RETRYAFTER_ERROR,
	SIP_ROUTE_ERROR,
	SIP_RSEQ_ERROR,
	SIP_SERVER_ERROR,
	SIP_SUBJECT_ERROR,
	SIP_SUBSCRIPTIONSTATE_ERROR,
	SIP_TIMESTAMP_ERROR,
	SIP_TO_ERROR,
	SIP_UNSUPPORTED_ERROR,
	SIP_USERAGENT_ERROR,
	SIP_VIA_ERROR,
	SIP_WARNING_ERROR,
	SIP_WWWAUTHENTICATE_ERROR,
#ifdef ICL_IMS 
	SIP_P_MEDIA_AUTHENTICATION_ERROR,
	SIP_PATH_ERROR,
	SIP_P_ACCESS_NETWORK_INFO_ERROR,
	SIP_P_ASSOCIATED_URI_ERROR,
	SIP_P_CALLED_PARTY_ID_ERROR,
	SIP_P_CHARGING_FUNCTION_ADDRESS_ERROR,
	SIP_P_CHARGING_VECTOR_ERROR,
	SIP_P_VISITED_NETWORK_ID_ERROR,
	SIP_SECURITY_CLIENT_ERROR,	
	SIP_SECURITY_SERVER_ERROR,
	SIP_SECURITY_VERIFY_ERROR,
	SIP_SERVICE_ROUTE_ERROR,
#endif /* end of ICL_IMS */
	SIP_UNKNOWN_HEADER,
	SIP_REQ_ERROR			= RC_BASE_SIP+400,
	SIP_RSP_ERROR			= RC_BASE_SIP+600
} SipRetMsg;

#ifdef  __cplusplus
}
#endif

#endif /* SIP_CM_H */
