/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define this if triggercps is defined in struct isdn_net_ioctl_cfg. */
/* #undef HAVE_TRIGGERCPS */

/* Define if you have the <sys/ioctl.h> header file.  */
#define HAVE_SYS_IOCTL_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the TIMRU facility.  */
/* #undef HAVE_TIMRU */

/* Define if you have the CISCOKEEPALIVE code */
/* #undef HAVE_CISCOKEEPALIVE */
