.\" $Id: rmdtovbox.man,v 1.3 2000/09/15 09:10:10 paul Exp $
.\" CHECKIN $Date: 2000/09/15 09:10:10 $
.TH rmdtovbox 1 "@MANDATE@" "ISDN 4 Linux @I4LVERSION@" "Linux System Administration"
.SH NAME
rmdtovbox \- isdn voice box (sound converter)
.SH SYNOPSIS
.B rmdtovbox
.I "[OPTION] [OPTION] [...] < INFILE > OUTFILE"
.SH "DESCRIPTION"
Convert rmd files (vbox 1.x voice files) to new vbox format.
.SH OPTIONS
.B rmdtovbox
reads from stdin and writes to stdout.
.TP
.B \-n, \-\-name NAME
set the caller name of the new file
.TP
.B \-c, \-\-callerid CALLERID
set the callerid of the new file.
.TP
.B \-p, \-\-phone PHONE
set the phone number of the new file.
.TP
.B \-l, \-\-location LOCATION
set the location of the new file.
.TP
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.B vboxtoau(1), vboxmode(1), vboxcnvt(1), vbox(5)
.SH AUTHOR
This manual page was written by Andreas Jellinghaus <aj@dungeon.inka.de>,
for Debian GNU/Linux and isdn4linux.
