#
# Makefile for the INCA-IP parallel port support under Linux.
#

all: port.o

#O_TARGET	:= incaip.a

export-objs	:= port.o

obj-y	 := port.o

EXTRA_AFLAGS := $(CFLAGS)


include $(TOPDIR)/Rules.make
