TOPDIR := ../..

SUBDIRS =

O_TARGET = tools.o

SOURCES = logger.c conn_req_server.c dl_conf.c agent_conf.c

#**********************
#bin_PROG = prog
#prog_SOURCE = prog.c xxx.c yyy.c
#prog_LIB = prog.o xxx.a yyy.a
#**********************
bin_PROG =

#**********************
#test_PROG = mytest
#mytestg_SOURCE = prog.c xxx.c yyy.c
#mytest_LIB = prog.o xxx.a yyy.a
#**********************
test_PROG = 

CFLAGS =
DEFS   = 
INCLUDE = 

LDFLAGS =
LDLIBS  = 

include $(TOPDIR)/rules.mk
