TOPDIR := ../../..

SUBDIRS =

O_TARGET = xmltool.o

SOURCES = mxml-string.c mxml-set.c mxml-search.c mxml-private.c
SOURCES += mxml-node.c mxml-file.c mxml-entity.c mxml-attr.c
LIBS = 

#**********************
#bin_PROG = prog
#prog_SOURCE = prog.c xxx.c yyy.c
#prog_LIB = prog.o xxx.a yyy.a
#**********************
bin_PROG =

#**********************
#test_PROG = mytest
#mytestg_SOURCE = prog.c xxx.c yyy.c
#mytest_LIB = prog.o xxx.a yyy.a
#**********************
test_PROG = 

CFLAGS =
DEFS   = 
INCLUDE = 

LDFLAGS = 
LDLIBS  = 

include $(TOPDIR)/rules.mk
