#!/bin/sh

. /etc/ath/apcfg
#APIP=192.168.1.10

athload
athstart

#
# configure bridge
#

ifconfig ixp0 0.0.0.0 up
ifconfig ixp1 0.0.0.0 up
ifconfig ath0 up
brctl addbr br0
brctl addif br0 ixp0
brctl addif br0 ixp1
brctl addif br0 ath0
#brctl setfd br0 0
#brctl stp br0 off

ifconfig br0 $AP_IPADDR netmask $AP_NETMASK up
#hostapd -B /etc/ath/wpa2-psk.conf &
#hostapd -B /etc/ath/wpa2EAP.conf &
