/* 
 * Copyright (C) 2000-2001 Computer & Communications Research Laboratories,
 *			   Industrial Technology Research Institute
 */
/*
 * sdp_def.h
 *
 * $Id: sdp_def.h,v 1.4 2001/10/23 00:39:28 hcc Exp $
 */

#ifndef SDP_DEF_H
#define SDP_DEF_H

#ifdef  __cplusplus
extern "C" {
#endif

/* SDP error codes */
#define RC_SDP_VALUE_NOT_SET				(RC_BASE_SDP+1)
#define RC_SDP_BUFFER_LENGTH_INSUFFICIENT		(RC_BASE_SDP+2)

#define RC_SDP_TO_ERR					(RC_BASE_SDP+51)
#define RC_SDP_TO_TOKEN_ERR				(RC_BASE_SDP+52)
#define RC_SDP_TO_USERNAME_TOKEN_ERR			(RC_BASE_SDP+53)
#define RC_SDP_TO_SESSIONID_TOKEN_ERR			(RC_BASE_SDP+54)
#define RC_SDP_TO_VERSION_TOKEN_ERR			(RC_BASE_SDP+55)
#define RC_SDP_TO_NETWORKTYPE_TOKEN_ERR			(RC_BASE_SDP+56)
#define RC_SDP_TO_ADDRESSTYPE_TOKEN_ERR			(RC_BASE_SDP+57)
#define RC_SDP_TO_ADDRESS_TOKEN_ERR			(RC_BASE_SDP+58)
	
#define RC_SDP_TC_ERR					(RC_BASE_SDP+101)
#define RC_SDP_TC_TOKEN_ERR				(RC_BASE_SDP+102)
#define RC_SDP_TC_NETWORKTYPE_TOKEN_ERR			(RC_BASE_SDP+103)
#define RC_SDP_TC_ADDRESSTYPE_TOKEN_ERR			(RC_BASE_SDP+104)
#define RC_SDP_TC_ADDRESS_TOKEN_ERR			(RC_BASE_SDP+105)
#define RC_SDP_TC_TTL_TOKEN_ERR				(RC_BASE_SDP+106)
#define RC_SDP_TC_NUMADDR_TOKEN_ERR			(RC_BASE_SDP+107)

#define RC_SDP_TR_ERR					(RC_BASE_SDP+151)
#define RC_SDP_TR_TOKEN_ERR				(RC_BASE_SDP+152)
#define RC_SDP_TR_REPEATINTERVAL_SIZE_TOKEN_ERR		(RC_BASE_SDP+153)
#define RC_SDP_TR_ACTIVEDURATION_SIZE_TOKEN_ERR		(RC_BASE_SDP+154)
#define RC_SDP_TR_OFFSET_SIZE_ERR			(RC_BASE_SDP+155)

#define RC_SDP_TZ_ERR					(RC_BASE_SDP+201)
#define RC_SDP_TZ_TOKEN_ERR				(RC_BASE_SDP+202)
#define RC_SDP_TZ_ADJUSTMENT_ERR			(RC_BASE_SDP+203)

#define RC_SDP_TA_ERR					(RC_BASE_SDP+251)
#define RC_SDP_TA_TOKEN_ERR				(RC_BASE_SDP+252)
#define RC_SDP_TA_ATTRIB_ERR				(RC_BASE_SDP+253)

#define RC_SDP_TT_ERR					(RC_BASE_SDP+301)
#define RC_SDP_TT_TOKEN_ERR				(RC_BASE_SDP+302)
#define RC_SDP_TT_STARTTIME_TOKEN_ERR			(RC_BASE_SDP+303)
#define RC_SDP_TT_ENDTIME_TOKEN_ERR			(RC_BASE_SDP+304)

#define RC_SDP_TK_ERR					(RC_BASE_SDP+351)
#define RC_SDP_TK_TOKEN_ERR				(RC_BASE_SDP+352)
#define RC_SDP_TK_METHOD_ERR				(RC_BASE_SDP+353)
#define RC_SDP_TK_KEY_ERR				(RC_BASE_SDP+354)

#define RC_SDP_TB_ERR					(RC_BASE_SDP+401)
#define RC_SDP_TB_TOKEN_ERR				(RC_BASE_SDP+402)
#define RC_SDP_TB_MODIFIER_ERR				(RC_BASE_SDP+403)
#define RC_SDP_TB_BANDWIDTH_ERR				(RC_BASE_SDP+404)

#define RC_SDP_TI_ERR					(RC_BASE_SDP+451)
#define RC_SDP_TI_TOKEN_ERR				(RC_BASE_SDP+452)
#define RC_SDP_TI_INFO_ERR				(RC_BASE_SDP+453)

#define RC_SDP_TS_ERR					(RC_BASE_SDP+501)
#define RC_SDP_TS_TOKEN_ERR				(RC_BASE_SDP+502)
#define RC_SDP_TS_NAME_ERR				(RC_BASE_SDP+503)

#define RC_SDP_TUERR					(RC_BASE_SDP+551)
#define RC_SDP_TU_TOKEN_ERR				(RC_BASE_SDP+552)
#define RC_SDP_TUURI_ERR				(RC_BASE_SDP+553)

#define RC_SDP_TE_ERR					(RC_BASE_SDP+601)
#define RC_SDP_TE_TOKEN_ERR				(RC_BASE_SDP+60)
#define RC_SDP_TE_EMAIL_ERR				(RC_BASE_SDP+603)

#define RC_SDP_TP_ERR					(RC_BASE_SDP+651)
#define RC_SDP_TP_TOKEN_ERR				(RC_BASE_SDP+652)
#define RC_SDP_TP_PHONENUM_ERR				(RC_BASE_SDP+653)

#define RC_SDP_TM_ERR					(RC_BASE_SDP+701)
#define RC_SDP_TM_TOKEN_ERR				(RC_BASE_SDP+702)
#define RC_SDP_TM_MEDIATYPE_ERR				(RC_BASE_SDP+703)
#define RC_SDP_TM_PORT_ERR				(RC_BASE_SDP+704)
#define RC_SDP_TM_NUMOFPORT_ERR				(RC_BASE_SDP+705)
#define RC_SDP_TM_PROTOCOL_ERR				(RC_BASE_SDP+706)
#define RC_SDP_TM_FMT_ERR				(RC_BASE_SDP+707)

#define RC_SDP_MSESS_CONNDATA_ERR			(RC_BASE_SDP+750)
#define RC_SDP_MSESS_BANDWIDTH_ERR			(RC_BASE_SDP+751)
#define RC_SDP_MSESS_ENCRYKEY_ERR			(RC_BASE_SDP+752)
#define RC_SDP_MSESS_ATTRIB_ERR				(RC_BASE_SDP+753)

#define RC_SDP_SESS_ERR					(RC_BASE_SDP+801)
#define RC_SDP_SESS_TV_ERR				(RC_BASE_SDP+802)
#define RC_SDP_SESS_TO_ERR				(RC_BASE_SDP+803)
#define RC_SDP_SESS_TI_ERR				(RC_BASE_SDP+804)
#define RC_SDP_SESS_TU_ERR				(RC_BASE_SDP+805)
#define RC_SDP_SESS_TE_ERR				(RC_BASE_SDP+806)
#define RC_SDP_SESS_TP_ERR				(RC_BASE_SDP+807)
#define RC_SDP_SESS_TC_ERR				(RC_BASE_SDP+808)
#define RC_SDP_SESS_TB_ERR				(RC_BASE_SDP+809)
#define RC_SDP_SESS_TT_ERR				(RC_BASE_SDP+810)
#define RC_SDP_SESS_TZ_ERR				(RC_BASE_SDP+811)
#define RC_SDP_SESS_TK_ERR				(RC_BASE_SDP+812)
#define RC_SDP_SESS_TA_ERR				(RC_BASE_SDP+813)
#define RC_SDP_SESS_TM_ERR				(RC_BASE_SDP+814)

#ifdef  __cplusplus
}
#endif

#endif /* SDP_DEF_H */
