/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Code maturity level options
 */
#undef  CONFIG_EXPERIMENTAL

/*
 * General configuration
 */
#undef  CONFIG_BUILDX11
#define CONFIG_KERNELDIR "/Danube/3.0.5/source/kernel/opensource/linux-2.4.31"
#define CONFIG_BINDIR "/root/danube_build/root_filesystem/usr/bin"
#define CONFIG_SBINDIR "/root/danube_build/root_filesystem/sbin"
#define CONFIG_MANDIR "/root/danube_build/root_filesystem/usr/man"
#define CONFIG_RUNDIR "/root/danube_build/root_filesystem/var/run"
#define CONFIG_LOCKDIR "/root/danube_build/root_filesystem/var/lock"
#define CONFIG_LOCKFILE "LCK.."
#define CONFIG_I4LCONFDIR "/root/danube_build/root_filesystem/etc/isdn"
#define CONFIG_CONFFILE "isdn.conf"
#define CONFIG_CALLERIDFILE "callerid.conf"
#define CONFIG_USERCONFFILE "~/.isdn"
#define CONFIG_COUNTRYCODE "49"
#define CONFIG_AREACODE ""
#define CONFIG_COUNTRY_PREFIX "+"
#define CONFIG_AREA_PREFIX "0"
#define CONFIG_DATADIR "/root/danube_build/root_filesystem/usr/lib/isdn"

/*
 * Runtime configuration tools
 */
#define CONFIG_ISDNCTRL 1
#undef  CONFIG_ISDNCTRL_CONF
#undef  CONFIG_ISDNCTRL_TIMRU
#undef  CONFIG_IPROFD
#define CONFIG_DIVERTCTRL 1

/*
 * Card configuration tools
 */
#define CONFIG_HISAXCTRL 1
#undef  CONFIG_ICNCTRL
#undef  CONFIG_PCBITCTL
#undef  CONFIG_AVMCAPICTRL
#undef  CONFIG_ACTCTRL
#undef  CONFIG_EICONCTRL

/*
 * Tools for monitoring activity
 */
#undef  CONFIG_IMON
#undef  CONFIG_IMONTTY
#undef  CONFIG_ISDNLOG
#undef  CONFIG_IPPPSTATS
#undef  CONFIG_XISDNLOAD
#undef  CONFIG_XMONISDN

/*
 * Applications
 */
#undef  CONFIG_VBOX
#undef  CONFIG_IPPPD

/*
 * Documentation
 */
#undef  CONFIG_GENMAN
#undef  CONFIG_FAQ
