include $(RT2860_DIR)/os/linux/config.mk

ifeq ($(RT2860_MODE), AP)
MOD_NAME = rt2860ap
else
ifeq ($(RT2860_MODE), STA)
MOD_NAME = rt2860sta
endif
endif

obj-m := $(MOD_NAME).o

rt2860ap-objs := ../../common/md5.o\
	../../common/mlme.o\
	../../common/rtmp_wep.o\
	../../common/action.o\
	../../common/ba_action.o\
	../../common/cmm_data.o\
	../../common/rtmp_init.o\
	../../common/rtmp_tkip.o\
	../../common/cmm_sync.o\
	../../common/eeprom.o\
	../../common/cmm_sanity.o\
	../../common/cmm_info.o\
	../../common/cmm_wpa.o\
	../../common/dfs.o\
	../../ap/ap.o\
	../../ap/ap_assoc.o\
	../../ap/ap_auth.o\
	../../ap/ap_authrsp.o\
	../../ap/ap_connect.o\
	../../ap/ap_mlme.o\
	../../ap/ap_sanity.o\
	../../ap/ap_sync.o\
	../../ap/ap_wpa.o\
	../../ap/ap_data.o\
	../../ap/ap_uapsd.o\
	../../ap/ap_mbss.o\
	../../os/linux/rt_linux.o\
        ../../os/linux/rt_profile.o\
	../../os/linux/rt_main_dev.o\
	../../os/linux/ap_ioctl.o\
	../../ap/ap_autoChSel.o

ifeq ($(HAS_ATE),y)
rt2860ap-objs += ../../os/linux/rt_ate.o
endif

ifeq ($(HAS_WSC),y)
rt2860ap-objs += ../../common/wsc.o\
	../../common/wsc_tlv.o\
	../../common/sha2.o\
	../../common/hmac.o\
	../../common/dh_key.o\
	../../common/evp_enc.o	
endif


ifeq ($(HAS_WDS),y)
rt2860ap-objs += ../../ap/ap_wds.o
endif

ifeq ($(HAS_APCLI),y)
rt2860ap-objs += \
	../../ap/ap_apcli.o \
	../../ap/apcli_mlme.o \
	../../ap/apcli_ctrl.o \
	../../ap/apcli_sync.o \
	../../ap/apcli_auth.o \
	../../ap/apcli_assoc.o \
	../../common/cmm_mat.o \
	../../common/cmm_mat_iparp.o \
	../../common/cmm_mat_pppoe.o \
	../../common/cmm_mat_ipv6.o
endif

ifeq ($(HAS_BLOCK_NET_IF),y)
rt2860ap-objs += ../../common/netif_block.o
endif

ifeq ($(HAS_IGMP_SNOOP_SUPPORT),y)
rt2860ap-objs += ../../common/igmp_snoop.o
endif

rt2860sta-objs := ../../common/md5.o\
	../../common/mlme.o\
	../../common/rtmp_wep.o\
	../../common/action.o\
	../../common/ba_action.o\
	../../common/cmm_data.o\
	../../common/rtmp_init.o\
	../../common/rtmp_tkip.o\
	../../common/cmm_sync.o\
	../../common/eeprom.o\
	../../common/cmm_sanity.o\
	../../common/cmm_info.o\
	../../common/cmm_wpa.o\
	../../common/dfs.o\
	../../sta/assoc.o\
	../../sta/aironet.o\
	../../sta/auth.o\
	../../sta/auth_rsp.o\
	../../sta/sync.o\
	../../sta/sanity.o\
	../../sta/rtmp_data.o\
	../../sta/connect.o\
	../../sta/wpa.o\
	../../os/linux/rt_linux.o\
        ../../os/linux/rt_profile.o\
	../../os/linux/rt_main_dev.o\
	../../os/linux/sta_ioctl.o

ifeq ($(HAS_ATE),y)
rt2860sta-objs += ../../os/linux/rt_ate.o
endif

ifeq ($(HAS_ETH_CONVERT_SUPPORT), y)
rt2860sta-objs += \
	../../common/cmm_mat.o \
	../../common/cmm_mat_iparp.o \
	../../common/cmm_mat_pppoe.o \
	../../common/cmm_mat_ipv6.o
endif

ifeq ($(HAS_WSC),y)
rt2860sta-objs += ../../common/wsc.o\
	../../common/wsc_tlv.o\
	../../common/sha2.o\
	../../common/hmac.o\
	../../common/dh_key.o\
	../../common/evp_enc.o	
endif

ifeq ($(HAS_BLOCK_NET_IF),y)
rt2860sta-objs += ../../common/netif_block.o
endif

clean:
	rm -f $(RT2860_DIR)/common/*.o
	rm -f $(RT2860_DIR)/common/.*.{cmd,flags,d}
	rm -f $(RT2860_DIR)/os/linux/*.{o,ko,mod.{o,c}}
	rm -f $(RT2860_DIR)/os/linux/.*.{cmd,flags,d}
	rm -fr $(RT2860_DIR)/os/linux/.tmp_versions
ifeq ($(RT2860_MODE),AP)
	rm -f $(RT2860_DIR)/ap/*.o
	rm -f $(RT2860_DIR)/ap/.*.{cmd,flags,d}
else
ifeq ($(RT2860_MODE),STA)
	rm -f $(RT2860_DIR)/sta/*.o
	rm -f $(RT2860_DIR)/sta/.*.{cmd,flags,d}
endif
endif
